// prisma/seeds/subscriptionPlans.seed.ts
// Run with: npx ts-node prisma/seeds/subscriptionPlans.seed.ts
// (or wire into your existing seed entrypoint)

import { PrismaClient, SubscriptionTier } from '@prisma/client';

const prisma = new PrismaClient();

const capabilities = {
  economy: {
    'academics.core': true,
    'students.core': true,
    'finance.collection': true,
    'finance.receipts': true,
    'finance.onlinePayment': false,
    'finance.dueManagement': false,
    'finance.advancedReports': false,
    'accounts.basic': false,
    'accounts.advanced': false,
    'frontOffice.enquiryLog': true,
    'frontOffice.pipeline': false,
    'offlineExams.core': true,
    'onlineExams.core': false,
    'onlineExams.advancedReports': false,
    'studyCenter.core': true,
    'studyCenter.advanced': false,
    'communication.sms': true,
    'communication.email': false,
    'communication.whatsapp': false,
    'certificates.standardTemplates': true,
    'certificates.customTemplates': false,
    'library.issueReturn': true,
    'library.digital': false,
    'hr.core': false,
    'hr.staffCore': true,
    'hr.reportsAnalytics': false,
    'inventory.core': false,
    'transport.core': false,
    'hostel.core': false,
    'helpCenter.core': true,
    'reports.basic': true,
    'reports.advanced': false,
    'settings.singleAdmin': true,
    'settings.roleManagement': false,
    'settings.multiBranch': false,
    'appCenter.core': false,
  },
  essential: {
    'academics.core': true,
    'academics.lessonPlans': true,
    'students.core': true,
    'finance.collection': true,
    'finance.receipts': true,
    'finance.onlinePayment': true,
    'finance.dueManagement': true,
    'finance.advancedReports': false,
    'accounts.basic': true,
    'accounts.advanced': false,
    'frontOffice.enquiryLog': true,
    'frontOffice.pipeline': true,
    'offlineExams.core': true,
    'onlineExams.core': true,
    'onlineExams.questionBank': true,
    'onlineExams.liveMonitoring': false,
    'onlineExams.advancedReports': false,
    'studyCenter.core': true,
    'studyCenter.advanced': false,
    'communication.sms': true,
    'communication.email': true,
    'communication.whatsapp': true,
    'certificates.standardTemplates': true,
    'certificates.customTemplates': true,
    'library.issueReturn': true,
    'library.digital': true,
    'library.reservations': true,
    'hr.core': true,
    'hr.staffCore': true,
    'hr.recruitment': false,
    'hr.performanceManagement': false,
    'hr.reportsAnalytics': false,
    'inventory.core': false,
    'transport.core': false,
    'hostel.core': false,
    'helpCenter.core': true,
    'reports.basic': true,
    'reports.advanced': false,
    'settings.singleAdmin': true,
    'settings.roleManagement': true,
    'settings.multiBranch': false,
    'appCenter.core': false,
  },
  professional: {
    'academics.core': true,
    'academics.lessonPlans': true,
    'academics.curriculumAnalytics': true,
    'students.core': true,
    'students.bulkTools': true,
    'finance.collection': true,
    'finance.receipts': true,
    'finance.onlinePayment': true,
    'finance.dueManagement': true,
    'finance.automation': true,
    'finance.advancedReports': true,
    'accounts.basic': true,
    'accounts.reconciliation': true,
    'accounts.multiBranch': true,
    'accounts.advanced': true,
    'frontOffice.enquiryLog': true,
    'frontOffice.pipeline': true,
    'frontOffice.complaintManagement': true,
    'offlineExams.core': true,
    'onlineExams.core': true,
    'onlineExams.questionBank': true,
    'onlineExams.liveMonitoring': true,
    'onlineExams.securityCenter': true,
    'onlineExams.advancedReports': true,
    'studyCenter.core': true,
    'studyCenter.advanced': true,
    'communication.sms': true,
    'communication.email': true,
    'communication.whatsapp': true,
    'communication.automatedTriggers': true,
    'certificates.standardTemplates': true,
    'certificates.customTemplates': true,
    'certificates.bulkGeneration': true,
    'library.issueReturn': true,
    'library.digital': true,
    'library.reservations': true,
    'library.inventoryTracking': true,
    'library.analytics': true,
    'hr.core': true,
    'hr.staffCore': true,
    'hr.recruitment': true,
    'hr.performanceManagement': true,
    'hr.reportsAnalytics': true,
    'inventory.core': true,
    'transport.core': true,
    'transport.liveTracking': true,
    'hostel.core': true,
    'helpCenter.core': true,
    'reports.basic': true,
    'reports.advanced': true,
    'settings.singleAdmin': true,
    'settings.roleManagement': true,
    'settings.multiBranch': true,
    'settings.apiAccess': true,
    'settings.whiteLabel': true,
    'appCenter.core': true,
  },
};

async function main() {
  await prisma.subscriptionPlan.upsert({
    where: { tier: SubscriptionTier.ECONOMY },
    update: {
      name: 'ShikshaMatrix Economy',
      maxStudents: 200,
      minStudents: 100,
      maxStaff: 30,
      storageGB: 2,
      monthlyPrice: 8,
      perStudentPrice: 8,
      capabilities: capabilities.economy,
      smsCredits: 200,
      whatsappCredits: 0,
    },
    create: {
      tier: SubscriptionTier.ECONOMY,
      name: 'ShikshaMatrix Economy',
      maxStudents: 200,
      minStudents: 100,
      maxStaff: 30,
      storageGB: 2,
      monthlyPrice: 8, // per-student rate, applied at billing time (not a flat fee)
      perStudentPrice: 8,
      capabilities: capabilities.economy,
      smsCredits: 200,
      whatsappCredits: 0,
    },
  });

  await prisma.subscriptionPlan.upsert({
    where: { tier: SubscriptionTier.ESSENTIAL },
    update: {
      name: 'ShikshaMatrix Essential',
      maxStudents: 500,
      minStudents: 0,
      maxStaff: 100,
      storageGB: 10,
      monthlyPrice: 1999,
      perStudentPrice: null,
      capabilities: capabilities.essential,
      smsCredits: 750,
      whatsappCredits: 300,
    },
    create: {
      tier: SubscriptionTier.ESSENTIAL,
      name: 'ShikshaMatrix Essential',
      maxStudents: 500,
      minStudents: 0,
      maxStaff: 100,
      storageGB: 10,
      monthlyPrice: 1999,
      perStudentPrice: null, // flat fee
      capabilities: capabilities.essential,
      smsCredits: 750,
      whatsappCredits: 300,
    },
  });

  await prisma.subscriptionPlan.upsert({
    where: { tier: SubscriptionTier.PROFESSIONAL },
    update: {
      name: 'ShikshaMatrix Professional',
      maxStudents: 1000,
      minStudents: 0,
      maxStaff: 0,
      storageGB: 100,
      monthlyPrice: 4299,
      perStudentPrice: null,
      capabilities: capabilities.professional,
      smsCredits: 2000,
      whatsappCredits: 1500,
    },
    create: {
      tier: SubscriptionTier.PROFESSIONAL,
      name: 'ShikshaMatrix Professional',
      maxStudents: 1000,
      minStudents: 0,
      maxStaff: 0, // unlimited
      storageGB: 100,
      monthlyPrice: 4299,
      perStudentPrice: null,
      capabilities: capabilities.professional,
      smsCredits: 2000,
      whatsappCredits: 1500,
    },
  });

  await prisma.subscriptionPlan.upsert({
    where: { tier: SubscriptionTier.ENTERPRISE },
    update: {
      name: 'ShikshaMatrix Enterprise',
      maxStudents: 0,
      minStudents: 0,
      maxStaff: 0,
      storageGB: 500,
      monthlyPrice: 0,
      perStudentPrice: null,
      capabilities: capabilities.professional,
      smsCredits: 5000,
      whatsappCredits: 3000,
    },
    create: {
      tier: SubscriptionTier.ENTERPRISE,
      name: 'ShikshaMatrix Enterprise',
      maxStudents: 0, // unlimited — 1000+ student chains, custom-quoted
      minStudents: 0,
      maxStaff: 0,
      storageGB: 500,
      monthlyPrice: 0, // set per-deal, not self-serve
      perStudentPrice: null,
      capabilities: capabilities.professional, // starts from Professional's superset, negotiate extras per deal
      smsCredits: 5000,
      whatsappCredits: 3000,
    },
  });

  console.log('Subscription plans seeded successfully.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });