import Fastify, { FastifyError, FastifyRequest, FastifyReply } from "fastify";
import multipart from "@fastify/multipart";
import { env, isGroqConfigured } from "./config/env.js";
import { logger } from "./lib/logger.js";
import { prisma } from "./lib/prisma.js";
import { registerCors } from "./plugins/cors.js";
import { registerSecurity } from "./plugins/security.js";
import { registerJwt } from "./plugins/jwt.js";
import { uploadRoutes } from "./routes/uploads.js";
import { healthRoutes } from "./routes/health.js";
import { loginRoutes } from "./routes/auth/login.js";
import { meRoutes } from "./routes/auth/me.js";
import { refreshRoutes } from "./routes/auth/refresh.js";
import { addIdentifierRoutes } from "./routes/auth/add-identifier.js";
import { registerSchoolRoutes } from "./routes/auth/register-school.js";
import { superAdminLoginRoutes } from "./routes/auth/superadmin-login.js";
import { agentLoginRoutes } from "./routes/auth/agent-login.js";
import { agentSelfServiceRoutes } from "./routes/agent/self-service.js";
import { superAdminSchoolRoutes } from "./routes/superadmin/schools.js";
import { superAdminStorageRoutes } from "./routes/superadmin/storage.js";
import { superAdminAgentRoutes } from "./routes/superadmin/agents.js";
import { superAdminAgentCommissionRoutes } from "./routes/superadmin/agent-commissions.js";
import { superAdminAgentPayoutRoutes } from "./routes/superadmin/agent-payouts.js";
import { adminClassRoutes } from "./routes/admin/classes.js";
import { adminStaffRoutes } from "./routes/admin/staff.js";
import { adminLeaveRoutes } from "./routes/admin/leaves.js";
import { adminCalendarRoutes } from "./routes/admin/calendar.js";
import { adminMessageRoutes } from "./routes/admin/messages.js";
import { adminAnnouncementRoutes } from "./routes/admin/announcements.js";
import { adminReportRoutes } from "./routes/admin/reports.js";
import { adminSettingsRoutes } from "./routes/admin/settings.js";
import { adminStudentsRoutes } from "./routes/admin/students.js";

import { adminAcademicSessionRoutes } from "./routes/admin/academic-sessions.js";
import { adminManagePeriodsRoutes } from "./routes/admin/manage-periods.js";
import { adminClassTimetableRoutes } from "./routes/admin/class-timetable.js";
import { adminPromoteStudentsRoutes } from "./routes/admin/promote-students.js";
import { adminStudentAdmissionRoutes } from "./routes/admin/admission.js";
import { adminStudentAttendanceRoutes } from "./routes/admin/student-attendance.js";
import { adminBehaviourRoutes } from "./routes/admin/behaviour.js";
import { adminDisabledStudentsRoutes } from "./routes/admin/disabled-students.js";
import { adminExamConfigRoutes } from "./routes/admin/exam-config.js";
import { adminExamScheduleRoutes } from "./routes/admin/exam-schedule.js";
import { adminMarksEntryRoutes } from "./routes/admin/marks-entry.js";
import { adminCoCurricularRoutes } from "./routes/admin/co-curricular.js";
import { adminRemarksApprovalRoutes } from "./routes/admin/remarks-approval.js";
import { adminReportCardRoutes } from "./routes/admin/report-card.js";
import { adminGenerateResultsRoutes } from "./routes/admin/generate-results.js";
import { adminExamAnalyticsRoutes } from "./routes/admin/exam-analytics.js";
import { adminExamDocsRoutes } from "./routes/admin/exam-docs.js";
import { adminExamAttendanceRoutes } from "./routes/admin/exam-attendance.js";
import { adminOnlineExamRoutes } from "./routes/admin/online-exam.js";
import { adminQuestionBankRoutes } from "./routes/admin/question-bank.js";
import { adminTestSchedulingRoutes } from "./routes/admin/test-schedule.js";
import { adminLiveMonitoringRoutes } from "./routes/admin/live-monitoring.js";
import { adminEvaluationRoutes } from "./routes/admin/evaluation.js";
import { adminOnlineExamAnalyticsRoutes } from "./routes/admin/online-exam-analytics.js";
import { adminSecurityCenterRoutes } from "./routes/admin/security-center.js";
import { adminReportsRoutes } from "./routes/admin/online-exams/reports.js";
import { adminExamSettingsRoutes } from "./routes/admin/online-exams/exam-settings.js";
import { adminEnquiryRoutes } from "./routes/admin/front-office/enquiry.js";
import { adminVisitorRoutes } from "./routes/admin/front-office/visitor.js";
import { adminComplaintRoutes }     from "./routes/admin/front-office/complaint.js";
import { adminCommunicationRoutes } from "./routes/admin/front-office/communication.js";
import { adminFOReportsRoutes }  from "./routes/admin/front-office/fo-reports.js";
import { adminFOSettingsRoutes, adminFOStaffRoutes } from "./routes/admin/front-office/fo-settings.js";
import { adminReimbursementRoutes, adminLoansRoutes, adminExpenseRoutes } from "./routes/admin/accounts/accounts-modules.js";
import { adminVendorPaymentRoutes }    from "./routes/admin/accounts/vendor-payments.js";
import { adminAccountPermissionRoutes } from "./routes/admin/accounts/account-permissions.js";
import { adminFinancialDocumentRoutes } from "./routes/admin/accounts/financial-documents.js";
import { adminAuditLogRoutes }        from "./routes/admin/accounts/audit-logs.js";
import { adminComplianceRoutes }      from "./routes/admin/accounts/compliance.js";
import { adminAccountsSettingsRoutes } from "./routes/admin/accounts/accounts-settings.js";
import { adminFinanceDashboardRoutes } from "./routes/admin/finance/finance-dashboard.js";
import { adminFeeCollectionRoutes }    from "./routes/admin/finance/fee-collection.js";
import { adminFeeStructureRoutes }     from "./routes/admin/finance/fee-structure.js";
import { adminDueManagementRoutes } from "./routes/admin/finance/due-management.js";
import { adminDiscountsRoutes }     from "./routes/admin/finance/discounts-scholarships.js";
import { adminTransactionsRoutes }  from "./routes/admin/finance/transactions.js";
import { adminStudentLedgerRoutes }    from "./routes/admin/finance/student-ledger.js";
import { adminFinanceReportsRoutes }   from "./routes/admin/finance/finance-reports.js";
import { adminFinanceManagementRoutes } from "./routes/admin/finance/finance-management.js";
import { adminFinanceAuditRoutes }    from "./routes/admin/finance/finance-audit.js";
import { adminOnlinePaymentsRoutes }  from "./routes/admin/finance/online-payments.js";
import { adminFinanceSettingsRoutes } from "./routes/admin/finance/finance-settings.js";
import { adminHrDashboardRoutes }    from "./routes/admin/hr/hr-dashboard-api.js";
import { adminStaffDirectoryRoutes } from "./routes/admin/hr/staff-directory-api.js";
import { adminHrAttendanceRoutes }   from "./routes/admin/hr/hr-attendance-api.js";
import { adminLeaveManagementRoutes } from "./routes/admin/hr/leave-management-api.js";
import { adminHrPayrollRoutes }       from "./routes/admin/hr/hr-payroll-api.js";
import { adminHrPayslipsRoutes }      from "./routes/admin/hr/payslips-api.js";
import { adminHrLoansRoutes }         from "./routes/admin/hr/hr-loans-api.js";
import { adminDeptDesignationsRoutes } from "./routes/admin/hr/dept-designations-api.js";
import { adminRecruitmentRoutes }      from "./routes/admin/hr/recruitment-api.js";
import { adminPerformanceRoutes }      from "./routes/admin/hr/performance-api.js";
import { adminHrDocsComplianceRoutes } from "./routes/admin/hr/hr-docs-compliance-api.js";
import { adminHrIdCardsRoutes }        from "./routes/admin/hr/hr-idcards-api.js";
import { adminHrReportsRoutes }    from "./routes/admin/hr/hr-reports-analytics-api.js";
import { adminHrAuditLogsRoutes }  from "./routes/admin/hr/hr-audit-logs-api.js";
import { adminHrSettingsRoutes }   from "./routes/admin/hr/hr-settings-api.js";
import { adminCertDashboardRoutes }  from "./routes/admin/certificates/cert-dashboard-api.js";
import { adminCertTemplatesRoutes }  from "./routes/admin/certificates/cert-templates-api.js";
import { adminCertGenerateRoutes }   from "./routes/admin/certificates/cert-generate-api.js";
import { adminStudyDashboardRoutes }   from "./routes/admin/study-center/study-dashboard-api.js";
import { adminStudySubjectMgmtRoutes } from "./routes/admin/study-center/study-subject-management-api.js";
import { adminStudyCurriculumRoutes }  from "./routes/admin/study-center/study-curriculum-api.js";
import { adminStudyMaterialsRoutes }   from "./routes/admin/study-center/study-materials-api.js";
import { adminStudyAssignmentsRoutes } from "./routes/admin/study-center/study-assignments-api.js";
import { adminStudyLessonPlansRoutes } from "./routes/admin/study-center/study-lesson-plans-api.js";
import { adminCommDashboardRoutes }    from "./routes/admin/communication/comm-dashboard-api.js";
import { adminCommNoticeBoardRoutes }  from "./routes/admin/communication/comm-noticeboard-api.js";
import { adminCommBroadcastRoutes }    from "./routes/admin/communication/comm-broadcast-api.js";
import { notificationRoutes } from "./routes/notifications.js";
import { adminCommMessageCenterRoutes } from "./routes/admin/communication/comm-message-center-api.js";
import { adminCommTemplatesRoutes }     from "./routes/admin/communication/comm-templates-api.js";
import { adminCommAnalyticsRoutes }     from "./routes/admin/communication/comm-analytics-api.js";
import { adminCommDeliveryLogsRoutes }       from "./routes/admin/communication/comm-delivery-logs-api.js";
import { adminCommScheduledMessagesRoutes }   from "./routes/admin/communication/comm-scheduled-messages-api.js";
import { adminCommSettingsRoutes }            from "./routes/admin/communication/comm-settings-api.js";
import { adminLibDashboardRoutes }    from "./routes/admin/library/lib-dashboard-api.js";
import { adminLibBookCatalogRoutes }  from "./routes/admin/library/lib-book-catalog-api.js";
import { adminLibIssueReturnRoutes }  from "./routes/admin/library/lib-issue-return-api.js";
import { adminLibMembersRoutes }       from "./routes/admin/library/lib-members-api.js";
import { adminLibDigitalLibraryRoutes } from "./routes/admin/library/lib-digital-library-api.js";
import { adminLibReservationsRoutes }  from "./routes/admin/library/lib-reservations-api.js";
import { adminLibFineManagementRoutes } from "./routes/admin/library/lib-fine-management-api.js";
import { adminLibInventoryRoutes }      from "./routes/admin/library/lib-inventory-api.js";
import { adminLibReportsRoutes }        from "./routes/admin/library/lib-reports-analytics-api.js";
import { adminLibSettingsRoutes }       from "./routes/admin/library/lib-settings-api.js";
import { adminInvDashboardRoutes }   from "./routes/admin/inventory/inv-dashboard-api.js";
import { adminInvItemMgmtRoutes }    from "./routes/admin/inventory/inv-item-management-api.js";
import { adminInvStockMgmtRoutes }   from "./routes/admin/inventory/inv-stock-management-api.js";
import { adminInvPurchaseRequestRoutes } from "./routes/admin/inventory/inv-purchase-requests-api.js";
import { adminInvVendorsRoutes }         from "./routes/admin/inventory/inv-vendors-api.js";
import { adminInvAssetAssignmentRoutes } from "./routes/admin/inventory/inv-asset-assignment-api.js";
import { adminInvMaintenanceRoutes }     from "./routes/admin/inventory/inv-maintenance-api.js";
import { adminInvStockAuditRoutes }      from "./routes/admin/inventory/inv-stock-audits-api.js";
import { adminInvReportsRoutes }         from "./routes/admin/inventory/inv-reports-analytics-api.js";
import { adminInvSettingsRoutes }        from "./routes/admin/inventory/inv-settings-api.js";
import { adminHostelDashboardRoutes }     from "./routes/admin/hostel/hostel-dashboard-api.js";
import { adminManageHostelsRoutes }       from "./routes/admin/hostel/hostel-manage-hostels-api.js";
import { adminRoomTypesRoutes }           from "./routes/admin/hostel/hostel-room-types-api.js";
import { adminManageRoomsRoutes }         from "./routes/admin/hostel/hostel-manage-rooms-api.js";
import { adminHostelAllocationRoutes }    from "./routes/admin/hostel/hostel-student-allocation-api.js";
import { adminHelpCategoriesRoutes } from "./routes/admin/help/help-categories-api.js";
import { adminHelpArticlesRoutes }   from "./routes/admin/help/help-articles-api.js";
import { adminHelpChatbotRoutes }    from "./routes/admin/help/help-ai-chatbot-api.js";
import { adminTransportDashboardRoutes } from "./routes/admin/transport/transport-dashboard-api.js";
import { adminTransportVehiclesRoutes }  from "./routes/admin/transport/transport-vehicles-api.js";
import { adminTransportRoutesRoutes }    from "./routes/admin/transport/transport-routes-api.js";
import { adminTransportTrackingRoutes }  from "./routes/admin/transport/transport-tracking-api.js";
import { adminSchoolSettingsRoutes }    from "./routes/admin/settings/settings-school-api.js";
import { adminBackupRoutes }            from "./routes/admin/settings/settings-backup-api.js";
import { adminCustomFieldsRoutes }      from "./routes/admin/settings/settings-custom-fields-api.js";
import { adminRolesPermissionsRoutes }  from "./routes/admin/settings/settings-roles-permissions-api.js";
import { adminPaymentGatewayRoutes }    from "./routes/admin/settings/settings-payment-gateway-api.js";
import { adminNotifSettingsRoutes }     from "./routes/admin/settings/settings-notification-api.js";
import { adminAdmissionSettingsRoutes } from "./routes/admin/settings/settings-admission-api.js";
import { adminAuditTrailRoutes }        from "./routes/admin/settings/settings-audit-trail-api.js";
import { adminModuleManagementRoutes }  from "./routes/admin/settings/settings-module-management-api.js";
import { superAdminAssignSubscriptionRoutes } from "./routes/superadmin/assignSubscription.route.js";
import { myCapabilitiesRoutes } from "./routes/admin/my-capabilities.js";
import { subscriptionSelfServiceRoutes } from "./routes/admin/subscription-self-service.js";
import { superAdminSubscriptionOverviewRoutes } from "./routes/superadmin/subscription-overview.js";
import { superAdminDiscountRoutes } from "./routes/superadmin/discount-codes.js";
import { razorpayWebhookRoutes } from "./routes/webhooks/razorpay.js";
import { registerSubscriptionCron } from "./jobs/subscriptionCron.js";
import { adminBiometricRoutes }         from "./routes/admin/settings/settings-biometric-api.js";
import { adminSchoolWebsiteRoutes }     from "./routes/admin/settings/settings-school-website-api.js";
import { adminDashboardRoutes } from "./routes/admin/dashboard-api.js";


import { profileRoutes }            from "./routes/dashboard/profile/profile.js";
import { profileDocumentsRoutes }   from "./routes/dashboard/profile/profile-documents.js";
import { profilePerformanceRoutes } from "./routes/dashboard/profile/profile-performance.js";
import { profilePayrollRoutes }     from "./routes/dashboard/profile/profile-payroll.js";
import { profileRequestsRoutes }    from "./routes/dashboard/profile/profile-requests.js";
import { tasksRoutes }         from "./routes/dashboard/tasks/task.js";
import { tasksGenerateRoutes } from "./routes/dashboard/tasks/tasks-generate.js";

import { studentsListRoutes }       from "./routes/dashboard/students/list.js";
import { studentsAttendanceRoutes } from "./routes/dashboard/students/attendance.js";
import { studentsBehaviourRoutes }  from "./routes/dashboard/students/behaviour.js";
import { academicsSubjectsRoutes } from "./routes/dashboard/academics/subjects.js";
import { academicsMarksRoutes }    from "./routes/dashboard/academics/marks.js";
import { academicsHomeworkRoutes } from "./routes/dashboard/academics/homework.js";
import { academicsTimetableRoutes } from "./routes/dashboard/academics/timetable.js";
import { financeOverviewRoutes } from "./routes/dashboard/finance/overview.js";
import { financeStudentRoutes }  from "./routes/dashboard/finance/student.js";
import { financeCollectRoutes }  from "./routes/dashboard/finance/collect.js";
import { hrStaffRoutes }      from "./routes/dashboard/hr/staff.js";
import { hrLeavesRoutes }     from "./routes/dashboard/hr/leaves.js";
import { hrPayrollRoutes }    from "./routes/dashboard/hr/payroll.js";
import { transportVehiclesRoutes } from "./routes/dashboard/transport/vehicles.js";
import { transportRoutesRoutes }   from "./routes/dashboard/transport/routes.js";
import { hostelRoomsRoutes }    from "./routes/dashboard/hostel/rooms.js";
import { hostelAllocateRoutes } from "./routes/dashboard/hostel/allocate.js";
import { messagesInboxRoutes }   from "./routes/dashboard/messages/inbox.js";
import { messagesChatRoutes }    from "./routes/dashboard/messages/chat.js";
import { messagesActionsRoutes } from "./routes/dashboard/messages/actions.js";
import { studentDashboardRoutes } from "./routes/student/dashboard.js";
import { studentAcademicsSummaryRoutes } from "./routes/student/academics.js";
import { parentChildrenRoutes }      from "./routes/parent/children.js";
import { parentDashboardRoutes }     from "./routes/parent/dashboard.js";
import { parentAcademicsRoutes }     from "./routes/parent/academics.js";
import { parentFeesRoutes }          from "./routes/parent/fees.js";
import { parentMoreRoutes }          from "./routes/parent/more.js";
import { staffDashboardRoutes } from "./routes/dashboard/dashboard.js";
import { academicsSyllabusRoutes } from "./routes/dashboard/academics/syllabus.js";
import { hrAttendanceRoutes } from "./routes/dashboard/hr/attendance.js";
import { messagesContactInfoRoutes } from "./routes/dashboard/messages/contact-info.js";
import { studentAttendanceRoutes } from "./routes/student/attendance.js";
import { studentAcademicsSubjectsRoutes } from "./routes/student/academics-subjects.js";
import { studentAcademicsMaterialsRoutes } from "./routes/student/academics-materials.js";
import { studentAcademicsLessonPlansRoutes } from "./routes/student/academics-lessonplans.js";
import { studentSyllabusRoutes } from "./routes/student/academics-syllabus.js";
import { studentCurriculumRoutes } from "./routes/student/academics-curriculum.js";
import { studentAssignmentsRoutes } from "./routes/student/academics-assignments.js";
import { studentOfflineExamsRoutes } from "./routes/student/academics-exams-offline.js";
import { studentExamScheduleRoutes } from "./routes/student/academics-exam-schedule.js";
import { studentOnlineExamsRoutes } from "./routes/student/academics-online-exams.js";
import { studentResultsRoutes } from "./routes/student/academics-results.js";
import { studentCertificatesRoutes } from "./routes/student/certificates.js";
import { studentLibraryRoutes } from "./routes/student/library.js";
import { studentCommunicationRoutes } from "./routes/student/communication.js";
import { studentStudyBuddyRoutes } from "./routes/student/study-buddy.js";
import { staffFinanceRoutes } from "./routes/staff/finance.js";
import { staffAccountsRoutes } from "./routes/staff/accounts.js";
import { staffLibraryRoutes } from "./routes/staff/library.js";
import { staffInventoryRoutes } from "./routes/staff/inventory.js";
import { staffHrRoutes } from "./routes/staff/hr.js";
import { staffSettingsRoutes } from "./routes/staff/settings.js";
import { staffHostelRoutes } from "./routes/staff/hostel.js";
import { staffTransportRoutes } from "./routes/staff/transport.js";
import { staffReportsRoutes } from "./routes/staff/reports.js";
import { appPushTokenRoutes } from "./routes/app/push-tokens.js";
import { studentFeesStructureRoutes } from "./routes/student/fees-structure.js";
import { studentFeesPaymentRoutes } from "./routes/student/fees-payment.js";
import { studentFeesReceiptsRoutes } from "./routes/student/fees-receipts.js";
import { studentFeesScholarshipsRoutes } from "./routes/student/fees-scholarships.js";
import { studentProfileRoutes } from "./routes/student/profile.js";
import { studentProfileSecurityRoutes } from "./routes/student/profile-security.js";
import { studentCalendarRoutes } from "./routes/student/academics-calendar.js";
import { studentTimetableRoutes } from "./routes/student/academics-timetable.js";

async function buildApp() {
  const app = Fastify({ logger: false });

  // Plugins
  await registerCors(app);
  await registerSecurity(app);
  await registerJwt(app);
  await app.register(multipart, {
    limits: { fileSize: 10 * 1024 * 1024 }, // 10MB hard ceiling at the plugin level; upload.service enforces tighter per-type limits
  });

  // Routes
  await app.register(uploadRoutes);
  await app.register(profileRoutes);
  await app.register(profileDocumentsRoutes);
  await app.register(profilePerformanceRoutes);
  await app.register(profilePayrollRoutes);
  await app.register(profileRequestsRoutes);
  await app.register(tasksRoutes);
  await app.register(tasksGenerateRoutes);
  await app.register(studentsListRoutes);
  await app.register(studentsAttendanceRoutes);
  await app.register(studentsBehaviourRoutes);
  await app.register(academicsSubjectsRoutes);
  await app.register(academicsMarksRoutes);
  await app.register(academicsHomeworkRoutes);
  await app.register(academicsTimetableRoutes);
  await app.register(financeOverviewRoutes);
  await app.register(financeStudentRoutes);
  await app.register(financeCollectRoutes);
  await app.register(hrStaffRoutes);
  await app.register(hrLeavesRoutes);
  await app.register(hrAttendanceRoutes);
  await app.register(hrPayrollRoutes);
  await app.register(transportVehiclesRoutes);
  await app.register(transportRoutesRoutes);
  await app.register(hostelRoomsRoutes);
  await app.register(hostelAllocateRoutes);
  await app.register(messagesInboxRoutes);
  await app.register(messagesChatRoutes);
  await app.register(messagesActionsRoutes);
  await app.register(studentDashboardRoutes);
  await app.register(studentAcademicsSummaryRoutes);
  await app.register(parentChildrenRoutes);
  await app.register(parentDashboardRoutes);
  await app.register(parentAcademicsRoutes);
  await app.register(parentFeesRoutes);
  await app.register(parentMoreRoutes);
  await app.register(staffDashboardRoutes);
  await app.register(academicsSyllabusRoutes);
  await app.register(registerSchoolRoutes);
  await app.register(superAdminSchoolRoutes);
  await app.register(superAdminStorageRoutes);
  await app.register(superAdminAgentRoutes);
  await app.register(superAdminAgentCommissionRoutes);
  await app.register(superAdminAgentPayoutRoutes);
  await app.register(superAdminLoginRoutes);
  await app.register(agentLoginRoutes);
  await app.register(agentSelfServiceRoutes);
  await app.register(healthRoutes);
  await app.register(loginRoutes);
  await app.register(meRoutes);
  await app.register(refreshRoutes);
  await app.register(addIdentifierRoutes);
  await app.register(messagesContactInfoRoutes);
  await app.register(studentAttendanceRoutes);
  await app.register(studentAcademicsSubjectsRoutes);
  await app.register(studentAcademicsMaterialsRoutes);
  await app.register(studentAcademicsLessonPlansRoutes);
  await app.register(studentSyllabusRoutes);
  await app.register(studentCurriculumRoutes);
  await app.register(studentAssignmentsRoutes);
  await app.register(studentOfflineExamsRoutes);
  await app.register(studentCertificatesRoutes);
  await app.register(studentLibraryRoutes);
  await app.register(studentCommunicationRoutes);
  await app.register(studentStudyBuddyRoutes);
  await app.register(staffFinanceRoutes);
  await app.register(staffAccountsRoutes);
  await app.register(staffLibraryRoutes);
  await app.register(staffInventoryRoutes);
  await app.register(staffHrRoutes);
  await app.register(staffSettingsRoutes);
  await app.register(staffHostelRoutes);
  await app.register(staffTransportRoutes);
  await app.register(staffReportsRoutes);
  await app.register(appPushTokenRoutes);
  await app.register(studentFeesStructureRoutes);
  await app.register(studentFeesPaymentRoutes);
  await app.register(studentFeesReceiptsRoutes);
  await app.register(studentFeesScholarshipsRoutes);
  await app.register(studentProfileRoutes);
  await app.register(studentProfileSecurityRoutes);
  await app.register(studentCalendarRoutes);
  await app.register(studentTimetableRoutes);
  
  await app.register(adminClassRoutes);
  await app.register(adminStaffRoutes);
  await app.register(adminLeaveRoutes);
  await app.register(adminCalendarRoutes);
  await app.register(adminMessageRoutes);
  await app.register(adminAnnouncementRoutes);
  await app.register(adminReportRoutes);
  await app.register(adminSettingsRoutes);
  await app.register(adminStudentsRoutes);
  await app.register(studentExamScheduleRoutes);
  await app.register(studentOnlineExamsRoutes);
  await app.register(studentResultsRoutes);

  await app.register(adminAcademicSessionRoutes);
  await app.register(adminManagePeriodsRoutes);
  await app.register(adminClassTimetableRoutes);
  await app.register(adminPromoteStudentsRoutes);
  await app.register(adminStudentAdmissionRoutes);
  await app.register(adminStudentAttendanceRoutes);
  await app.register(adminBehaviourRoutes);
  await app.register(adminDisabledStudentsRoutes);
  await app.register(adminExamConfigRoutes);
  await app.register(adminExamScheduleRoutes);
  await app.register(adminMarksEntryRoutes);
  await app.register(adminCoCurricularRoutes);
  await app.register(adminRemarksApprovalRoutes);
  await app.register(adminReportCardRoutes);
  await app.register(adminGenerateResultsRoutes);
  await app.register(adminExamAnalyticsRoutes);
  await app.register(adminExamDocsRoutes);
  await app.register(adminExamAttendanceRoutes);
  await app.register(adminOnlineExamRoutes);
  await app.register(adminQuestionBankRoutes);
  await app.register(adminTestSchedulingRoutes);
  await app.register(adminLiveMonitoringRoutes);
  await app.register(adminEvaluationRoutes);
  await app.register(adminOnlineExamAnalyticsRoutes);
  await app.register(adminSecurityCenterRoutes);
  await app.register(adminReportsRoutes);
  await app.register(adminExamSettingsRoutes);
  await app.register(adminEnquiryRoutes);
  await app.register(adminVisitorRoutes);
  await app.register(adminComplaintRoutes);
  await app.register(adminCommunicationRoutes);
  await app.register(adminFOReportsRoutes);
  await app.register(adminFOSettingsRoutes);
  await app.register(adminFOStaffRoutes);
  await app.register(adminReimbursementRoutes);
  await app.register(adminLoansRoutes);
  await app.register(adminExpenseRoutes);
  await app.register(adminVendorPaymentRoutes);
  await app.register(adminAccountPermissionRoutes);
  await app.register(adminFinancialDocumentRoutes);
  await app.register(adminAuditLogRoutes);
  await app.register(adminComplianceRoutes);
  await app.register(adminAccountsSettingsRoutes);
  await app.register(adminFinanceDashboardRoutes);
  await app.register(adminFeeCollectionRoutes);
  await app.register(adminFeeStructureRoutes);
  await app.register(adminDueManagementRoutes);
  await app.register(adminDiscountsRoutes);
  await app.register(adminTransactionsRoutes);
  await app.register(adminStudentLedgerRoutes);
  await app.register(adminFinanceReportsRoutes);
  await app.register(adminFinanceManagementRoutes);
  await app.register(adminFinanceAuditRoutes);
  await app.register(adminOnlinePaymentsRoutes);
  await app.register(adminFinanceSettingsRoutes);
  await app.register(adminHrDashboardRoutes);
  await app.register(adminStaffDirectoryRoutes);
  await app.register(adminHrAttendanceRoutes);
  await app.register(adminLeaveManagementRoutes);
  await app.register(adminHrPayrollRoutes);
  await app.register(adminHrPayslipsRoutes);
  await app.register(adminHrLoansRoutes);
  await app.register(adminDeptDesignationsRoutes);
  await app.register(adminRecruitmentRoutes);
  await app.register(adminPerformanceRoutes);
  await app.register(adminHrDocsComplianceRoutes);
  await app.register(adminHrIdCardsRoutes);
  await app.register(adminHrReportsRoutes);
  await app.register(adminHrAuditLogsRoutes);
  await app.register(adminHrSettingsRoutes);
  await app.register(adminCertDashboardRoutes);
  await app.register(adminCertTemplatesRoutes);
  await app.register(adminCertGenerateRoutes);
  await app.register(adminStudyDashboardRoutes);
  await app.register(adminStudySubjectMgmtRoutes);
  await app.register(adminStudyCurriculumRoutes);
  await app.register(adminStudyMaterialsRoutes);
  await app.register(adminStudyAssignmentsRoutes);
  await app.register(adminStudyLessonPlansRoutes);
  await app.register(adminCommDashboardRoutes);
  await app.register(adminCommNoticeBoardRoutes);
  await app.register(adminCommBroadcastRoutes);
  await app.register(notificationRoutes);
  await app.register(adminCommMessageCenterRoutes);
  await app.register(adminCommTemplatesRoutes);
  await app.register(adminCommAnalyticsRoutes);
  await app.register(adminCommDeliveryLogsRoutes);
  await app.register(adminCommScheduledMessagesRoutes);
  await app.register(adminCommSettingsRoutes);
  await app.register(adminLibDashboardRoutes);
  await app.register(adminLibBookCatalogRoutes);
  await app.register(adminLibIssueReturnRoutes);
  await app.register(adminLibMembersRoutes);
  await app.register(adminLibDigitalLibraryRoutes);
  await app.register(adminLibReservationsRoutes);
  await app.register(adminLibFineManagementRoutes);
  await app.register(adminLibInventoryRoutes);
  await app.register(adminLibReportsRoutes);
  await app.register(adminLibSettingsRoutes);
  await app.register(adminInvDashboardRoutes);
  await app.register(adminInvItemMgmtRoutes);
  await app.register(adminInvStockMgmtRoutes);
  await app.register(adminInvPurchaseRequestRoutes);
  await app.register(adminInvVendorsRoutes);
  await app.register(adminInvAssetAssignmentRoutes);
  await app.register(adminInvMaintenanceRoutes);
  await app.register(adminInvStockAuditRoutes);
  await app.register(adminInvReportsRoutes);
  await app.register(adminInvSettingsRoutes);
  await app.register(adminHostelDashboardRoutes);
  await app.register(adminManageHostelsRoutes);
  await app.register(adminRoomTypesRoutes);
  await app.register(adminManageRoomsRoutes);
  await app.register(adminHostelAllocationRoutes);
  await app.register(adminHelpCategoriesRoutes);
  await app.register(adminHelpArticlesRoutes);
  await app.register(adminHelpChatbotRoutes);
  await app.register(adminTransportDashboardRoutes);
  await app.register(adminTransportVehiclesRoutes);
  await app.register(adminTransportRoutesRoutes);
  await app.register(adminTransportTrackingRoutes);
  await app.register(adminSchoolSettingsRoutes);
  await app.register(adminBackupRoutes);
  await app.register(adminCustomFieldsRoutes);
  await app.register(adminRolesPermissionsRoutes);
  await app.register(adminPaymentGatewayRoutes);
  await app.register(adminNotifSettingsRoutes);
  await app.register(adminAdmissionSettingsRoutes);
  await app.register(adminAuditTrailRoutes);
  await app.register(adminModuleManagementRoutes);
  await app.register(superAdminAssignSubscriptionRoutes);
  await app.register(myCapabilitiesRoutes);
  await app.register(subscriptionSelfServiceRoutes);
  await app.register(superAdminSubscriptionOverviewRoutes);
  await app.register(superAdminDiscountRoutes);
  await app.register(razorpayWebhookRoutes);
  await app.register(adminBiometricRoutes);
  await app.register(adminSchoolWebsiteRoutes);
  await app.register(adminDashboardRoutes);
  
  // Error handler
  app.setErrorHandler(
    (error: FastifyError, _request: FastifyRequest, reply: FastifyReply) => {
      logger.error({ err: error }, "Unhandled error");
      const statusCode = error.statusCode || 500;
      reply.status(statusCode).send({
        success: false,
        error: error.name || "InternalServerError",
        message: error.message,
      });
    }
  );

  // 404 handler
  app.setNotFoundHandler(
    (request: FastifyRequest, reply: FastifyReply) => {
      reply.status(404).send({
        success: false,
        error: "NotFound",
        message: `Route ${request.method} ${request.url} not found`,
      });
    }
  );

  return app;
}

async function start() {
  const app = await buildApp();
  try {
    logger.info("Connecting to database...");
    await prisma.$connect();
    logger.info("Database connected");
    await app.listen({ port: env.PORT, host: "0.0.0.0" });
    registerSubscriptionCron();
    logger.info(`
╔══════════════════════════════════════╗
║  🎓 ShikshaMatrix API               ║
║  http://localhost:${env.PORT}             ║
╚══════════════════════════════════════╝
    `);
    logger.info(isGroqConfigured ? "Groq AI (Help Center chatbot) - configured" : "Groq AI (Help Center chatbot) - GROQ_API_KEY not set, chatbot will show a setup message");
  } catch (error) {
    logger.error({ err: error }, "Failed to start");
    await prisma.$disconnect();
    process.exit(1);
  }
}

process.on("SIGINT", async () => {
  await prisma.$disconnect();
  process.exit(0);
});

start();